### PR TITLE
Henrybranch

### PR DESCRIPTION
**Pull request by henryn1996**

### CODE REVIEW

**Comment by Edmyao** [comment]
didnt work

**Comment by henryn1996** [comment]
[Not render login page after create new user error](https://trello.com/c/MWYbyXAV/58-not-render-login-page-after-create-new-user-error)

**Comment by henryn1996** [comment]
[Not render login page after create new user error](https://trello.com/c/MWYbyXAV/58-not-render-login-page-after-create-new-user-error)

**Comment by henryn1996** [comment]
[not re-render pages after saving location](https://trello.com/c/GWLU3baf/27-not-re-render-pages-after-saving-location)

**Pull request closed without merging**
